#!/bin/bash

./find.py /Users/atdog/Desktop/eva_1/appinventor.ai_progetto2003.SCAN.apk 1 > log1/appinventor.ai_progetto2003.SCAN.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/bnw.project.wallpaper.buddycons.apk 1 > log1/bnw.project.wallpaper.buddycons.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/cn.etouch.ecalendar2.apk 1 > log1/cn.etouch.ecalendar2.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/cn.jingling.motu.photowonder.apk 1 > log1/cn.jingling.motu.photowonder.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.antivirus.apk 1 > log1/com.antivirus.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.avast.android.mobilesecurity.apk 1 > log1/com.avast.android.mobilesecurity.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.bumptech.bumpga.apk 1 > log1/com.bumptech.bumpga.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.cfinc.petapic.apk 1 > log1/com.cfinc.petapic.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.cyworld.camera.apk 1 > log1/com.cyworld.camera.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.facebook.katana.apk 1 > log1/com.facebook.katana.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.facebook.orca.apk 1 > log1/com.facebook.orca.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.fetself.apk 1 > log1/com.fetself.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.gameloft.android.ANMP.GloftUFHM.apk 1 > log1/com.gameloft.android.ANMP.GloftUFHM.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.gamevil.cartoonwars.blade.global.apk 1 > log1/com.gamevil.cartoonwars.blade.global.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.gamevil.cartoonwars.two.global.apk 1 > log1/com.gamevil.cartoonwars.two.global.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.gau.go.launcherex.apk 1 > log1/com.gau.go.launcherex.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.godgame.bigtwo.android.apk 1 > log1/com.godgame.bigtwo.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.godgame.landlord.android.apk 1 > log1/com.godgame.landlord.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.godgame.mj.android.apk 1 > log1/com.godgame.mj.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.godgame.poker13.android.apk 1 > log1/com.godgame.poker13.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.godgame.texasholdem.android.apk 1 > log1/com.godgame.texasholdem.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.google.android.apps.docs.apk 1 > log1/com.google.android.apps.docs.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.google.android.apps.maps.apk 1 > log1/com.google.android.apps.maps.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.google.android.apps.translate.apk 1 > log1/com.google.android.apps.translate.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.google.zxing.client.android.apk 1 > log1/com.google.zxing.client.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.hengtalk.girlwidget.apk 1 > log1/com.hengtalk.girlwidget.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.herman.ringtone.apk 1 > log1/com.herman.ringtone.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.icloudzone.SpeedNight2.apk 1 > log1/com.icloudzone.SpeedNight2.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.igs.big2.apk 1 > log1/com.igs.big2.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.igs.mjstar31.apk 1 > log1/com.igs.mjstar31.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.igs.poker13.apk 1 > log1/com.igs.poker13.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.instagram.android.apk 1 > log1/com.instagram.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.intsig.BCRLite.apk 1 > log1/com.intsig.BCRLite.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.jiubang.goscreenlock.apk 1 > log1/com.jiubang.goscreenlock.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.kakao.talk.apk 1 > log1/com.kakao.talk.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.kfactormedia.mycalendarmobile.apk 1 > log1/com.kfactormedia.mycalendarmobile.log 2>&1
# ./find.py /Users/atdog/Desktop/eva_1/com.lookout.apk 1 > log1/com.lookout.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.moaibot.mahjong.apk 1 > log1/com.moaibot.mahjong.log 2>&1
# ./find.py /Users/atdog/Desktop/eva_1/com.mplusapp.apk 1 > log1/com.mplusapp.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.nhncorp.skundeadgr.apk 1 > log1/com.nhncorp.skundeadgr.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.qvod.player.apk 1 > log1/com.qvod.player.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.sgiggle.production.apk 1 > log1/com.sgiggle.production.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.skype.raider.apk 1 > log1/com.skype.raider.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.tencent.mm.apk 1 > log1/com.tencent.mm.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.ting.mp3.qianqian.android.apk 1 > log1/com.ting.mp3.qianqian.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.twitter.android.apk 1 > log1/com.twitter.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.viber.voip.apk 1 > log1/com.viber.voip.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.whatsapp.apk 1 > log1/com.whatsapp.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.xzPopular.apk 1 > log1/com.xzPopular.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/com.yahoo.mobile.client.android.im.apk 1 > log1/com.yahoo.mobile.client.android.im.log 2>&1
# ./find.py /Users/atdog/Desktop/eva_1/com.yahoo.mobile.client.android.mail.apk 1 > log1/com.yahoo.mobile.client.android.mail.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/easytravel.category.index.apk 1 > log1/easytravel.category.index.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/gogolook.callgogolook2.apk 1 > log1/gogolook.callgogolook2.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/jp.naver.line.android.apk 1 > log1/jp.naver.line.android.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/la.droid.qr.apk 1 > log1/la.droid.qr.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/mobi.infolife.eraser.apk 1 > log1/mobi.infolife.eraser.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/tv.pps.mobile.apk 1 > log1/tv.pps.mobile.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/tw.chaozhuyin.apk 1 > log1/tw.chaozhuyin.log 2>&1
./find.py /Users/atdog/Desktop/eva_1/tw.com.quickmark.apk 1 > log1/tw.com.quickmark.log 2>&1
